version: '3'

services:
  app:
    build: .
    container_name: node
    depends_on:
      - mongo
    volumes:
      - app/node_modules
      - .:/app
    ports:
      - '80:80'
    # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  #Mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data-db:/data/db

