version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data-db:/data/db
  app:
    depends_on:
      - mongo
    container_name: node
    build: .
    ports:
      - '80:80'
    links:
      - mongo
  
