module.exports = {
    Admin: require('./admin'),
    Bank: require('./bank'),
    BankAccount: require('./bank-account'),
    BillPlzBill: require('./billplz-bill'),
    Business: require('./business'),
    BusinessCategory: require('./business-category'),
    BusinessType: require('./business-type'),
    Card: require('./card'),
    CategoryType: require('./category-type'),
    Currency: require('./currency'),
    Feedback: require('./feedback'),
    Item: require('./item'),
    Merchant: require('./merchant'),
    PaymentMethod: require('./payment-method'),
    PaymentReason: require('./payment-reason'),
    Push: require('./push'),
    Static: require('./static'),
    User: require('./user'),
    UserPayment: require('./user-payment')
};